### ISSUE TITLE
[Bug]: API seems to just not work when I call sample examples. 

### ISSUE THREAD

**Issue by akaushik1998** [blocknative/python-sdk#11]
As stated in title API seems to just not work. After running the program it remains running for 15-20 seconds then outputs False as shown in the screenshot. My API-Key is correct as I've made successful calls with it with the API. 

using Python version 3.9.6 
macOS Big Sur V 11.5.2

![Screen Shot 2021-11-04 at 8 43 12 PM](https://user-images.githubusercontent.com/61363904/140445323-5901c752-06a3-4fac-ab40-6dfa40c7e4ab.png)

**Comment by jac18281828** [comment]
Try downloading this and running it from within Docker.   https://gist.github.com/jac18281828/7e7d9fb5f5ed75b9e14b570b4e5fe687

Any difference in output?

**Comment by akaushik1998** [comment]
Hi thanks for this. It *sort of* works. It outputs one transaction then doesn't output anything else. I then have to kill the process to regain the shell. 

It's also not clear to me why just running this normally from PyCharm doesn't work?

**Comment by jac18281828** [comment]
Cool, glad to hear that it is working for you now.    I see what you mean about the one transaction.  That is actually how it is designed.   It subscribes for one transaction and then once it is completed removes the subscription.   

Regarding PyCharm, it sounds like something in the environment is not quite right.    You could look at the settings (versions) in the Dockerfile and make sure you are on spec.    I load the Dockerfile from VS Code (Open in Container) and it works the same.  I'm able to debug and see the output as I do from the command line.

Is your goal to subscribe to multiple transactions?

> Hi thanks for this. It _sort of_ works. It outputs one transaction then doesn't output anything else. I then have to kill the process to regain the shell.
> 
> It's also not clear to me why just running this normally from PyCharm doesn't work?

**Comment by akaushik1998** [comment]
Got it, I'll look at the dependencies and see if I'm missing anything.  

My goal is to listen to all transactions for a given address in the mempool from (inputs) t0 to t1 and then use those pending transactions as input to another piece of code. Is there a better way of doing this?

**Comment by akaushik1998** [comment]
Looking at the dependencies the only thing that stands out why it might work in the Docker but not in pycharm is that I have an m1 chip? I'm not too familiar with docker but could this be the reason?

**Comment by jac18281828** [comment]
I checked a bit deeper into the unsubscription issue and I believe it is a bug.   I submitted pr #14 

Regarding the m1 chip.   I don't have a test environment for that but I am suspicious that this is working from within Docker.   I did do some digging into the websockets package that is used here and that is native python.  I'd expect it to work if m1 python is working.    What version of python are you running?   Perhaps try virtualenv to another version?    I used 3.9.2 on my container.   I note that my Intel Mac is shipping with 3.8.6.

**Comment by akaushik1998** [comment]
I tried installing and running it with 3.9.2 and same error so don't think it's that. I was using 3.9.6 before. 

If possible could you please post an example code of how you would make a call to listen for K transactions and then unsubscribe? It's not clear to me from reading your commit.

**Comment by jac18281828** [comment]
Is this what you are looking for?   https://gist.github.com/jac18281828/47a650e2525aa23a2b0039236fb29e6b

All the issues you reported have now been fixed.   Can we close this ticket?

**Comment by akaushik1998** [comment]
Yes that's exactly it. Thanks for your help! 

And yeah you can feel free to close it. Fwiw I did some more diving into why the code wasn't working in my PyCharm environment and I've found where the API fails. It appears to be in the call to _connect in the connect() function. Appears that the call to `open_websocket_url(self.base_url)` fails with a timeout error. I've attached the error messages and wondering if you have any familiarity with this sort of thing. 
![Screen Shot 2021-11-09 at 10 07 03 PM](https://user-images.githubusercontent.com/61363904/141048020-d3662978-9bb1-43b7-b3d1-911f9535af9c.png)
![Screen Shot 2021-11-09 at 10 06 43 PM](https://user-images.githubusercontent.com/61363904/141048026-1566cf37-ad02-44a1-b54b-26c9b65fa95e.png)
.
