### ISSUE TITLE
[Bug]: Cannot import blocknative

### ISSUE THREAD

**Issue by arenstar** [blocknative/python-sdk#23]
### Current Behavior

when i try the examples i get

ModuleNotFoundError: No module named 'blocknative.stream'; 'blocknative' is not a package

### Expected Behavior

should work

### Steps To Reproduce

pip3 install blocknative-sdk

python examples/subscribe.py

### Python Version

3.9

**Comment by jac18281828** [comment]
I can not be sure, but it appears to me that you are using a combination of pip and the python-sdk repo.    I'd suggest just using pip.

Something like this:

```
$ virtualenv bn
$ . ./bn/bin/activate
(bn) $ pip3 install --upgrade pip
(bn) $ pip3 install blocknative-sdk
(bn) $ curl 'https://raw.githubusercontent.com/blocknative/python-sdk/main/examples/subscribe.py' > subscribe.py
(bn) $ python3 subscribe.py myapikey.key
```

**Comment by jac18281828** [comment]
BTW, if you intension is to use the REPO locally you have several options.

You could load it from the Dockerfile (best), you could manually install it, python3 setup.py install, or you could set the PYTHONPATH=.

I will close this ticket, please let me know if you are not able to get things going.
