### ISSUE TITLE
[Bug]: KeyError: 'blockPrices' when calling Gas Station API sequentially

### ISSUE THREAD

**Issue by DefiBax** [blocknative/python-sdk#32]
### Current Behavior

I am able to individually access the maxPriorityFeePerGas and price elements of the Gas Station API payload. If I try and access both, or each individual element twice in one function, I receive ```KeyError: 'blockPrices'``` for the second call.

### Expected Behavior

I expect to receive the second element called in the function.

### Steps To Reproduce

1. In this environment....python version 3.8.9
2. With this config....brownie version v1.17.2
3. Run ```
def get_gas_tip_test(self):
        gas_ninty_nine = self.data["blockPrices"][0]["estimatedPrices"][0]["maxPriorityFeePerGas"]
        return gas_ninty_nine
def get_gas_price_test(self):
        gas_ninty_nine = self.data["blockPrices"][0]["estimatedPrices"][0]["price"]
        return gas_ninty_nine

def main():
    gas_tip_required()
    gas_tip_required()
    # gas_price_required()

def gas_tip_required():
    print(Gas(MINING_CONFIDENCE).get_gas_tip_test())

def gas_price_required():
    print(Gas(MINING_CONFIDENCE).get_gas_price_test())

if __name__ == "__main__":
    main()```

Ignore MINING_CONFIDENCE in this code, its a placeholder for more advanced logic but doesn't impact the get_gas_tip_test() or get_gas_price_test() functions.

4. See error `KeyError: 'blockPrices'`

### Python Version

3.8.9

### Relevant log output

```shell
Running 'get_gas.py::main'...
2
  File "brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./get_gas.py", line 6, in main
    gas_tip_required()
  File "./get_gas.py", line 10, in gas_tip_required
    print(Gas(MINING_CONFIDENCE).get_gas_tip_test())
  File "./helpful_scripts.py", line 44, in get_gas_tip_test
    gas_ninty_nine = self.data["blockPrices"][0]["estimatedPrices"][0]["maxPriorityFeePerGas"]
KeyError: 'blockPrices'
```

**Comment by taylorjdawson** [comment]
@DefiBax This does not look like it is related to the python sdk, could you post this in [our discord](https://discord.gg/REtJmNrcND) instead? Thanks!
