### ISSUE TITLE
[Bug]: Abi doesn't seem to be considered

### ISSUE THREAD

**Issue by rickbeeloo** [blocknative/python-sdk#41]
### Current Behavior

When passing the `abi` it does still return the encoded `input`, whereas on the blocknative web version it will show the decoded output. 

### Expected Behavior

Show decoded `input` based on provided ABI, as on the webpage

### Python Version

3.10

**Comment by taylorjdawson** [comment]
@rickbeeloo Can you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) of this? Thanks!

**Comment by taylorjdawson** [comment]
@rickbeeloo getting addressed in `v0.2.7`.
